import {
  commentsFailure,
  commentsRequest,
  commentsSuccess,
  COMMENTS_FAILURE,
  COMMENTS_REQUEST,
  COMMENTS_SUCCESS,
} from './commentsAction';
import {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  loginRequest,
  loginSuccess,
  loginFailure,
  logout,
} from './loginActions';
import {
  postsFailure,
  postsRequest,
  postsSuccess,
  POSTS_FAILURE,
  POSTS_REQUEST,
  POSTS_SUCCESS,
} from './postsActions';
import {
  SUBREDDITS_REQUEST,
  SUBREDDITS_SUCCESS,
  SUBREDDITS_FAILURE,
  subRedditsRequest,
  subRedditsSuccess,
  subRedditsFailure,
} from './subRedditsActions';

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  loginRequest,
  loginSuccess,
  loginFailure,
  logout,
  SUBREDDITS_REQUEST,
  SUBREDDITS_SUCCESS,
  SUBREDDITS_FAILURE,
  subRedditsRequest,
  subRedditsSuccess,
  subRedditsFailure,
  POSTS_REQUEST,
  POSTS_SUCCESS,
  POSTS_FAILURE,
  postsRequest,
  postsSuccess,
  postsFailure,
  COMMENTS_REQUEST,
  COMMENTS_SUCCESS,
  COMMENTS_FAILURE,
  commentsRequest,
  commentsSuccess,
  commentsFailure,
};
