import {
  SORT_PERIOD_KEYS,
  SORT_PERIOD_VALUES,
  SORT_TYPE_KEYS,
  SORT_TYPE_VALUES,
} from '../../constants';

const sortTypeData = [
  {key: SORT_TYPE_KEYS.HOT, value: SORT_TYPE_VALUES.HOT},
  {key: SORT_TYPE_KEYS.NEW, value: SORT_TYPE_VALUES.NEW},
  {key: SORT_TYPE_KEYS.TOP, value: SORT_TYPE_VALUES.TOP},
  {key: SORT_TYPE_KEYS.CONTROVERSIAL, value: SORT_TYPE_VALUES.CONTROVERSIAL},
  {key: SORT_TYPE_KEYS.RISING, value: SORT_TYPE_VALUES.RISING},
];

const sortPeriodData = [
  {key: SORT_PERIOD_KEYS.HOUR, value: SORT_PERIOD_VALUES.PAST_HOUR},
  {key: SORT_PERIOD_KEYS.DAY, value: SORT_PERIOD_VALUES.PAST_24_HOURS},
  {key: SORT_PERIOD_KEYS.WEEK, value: SORT_PERIOD_VALUES.PAST_WEEK},
  {key: SORT_PERIOD_KEYS.MONTH, value: SORT_PERIOD_VALUES.PAST_MONTH},
  {key: SORT_PERIOD_KEYS.YEAR, value: SORT_PERIOD_VALUES.PAST_YEAR},
  {key: SORT_PERIOD_KEYS.ALL, value: SORT_PERIOD_VALUES.ALL_TIME},
];

export {sortTypeData, sortPeriodData};
