import env from 'react-native-config';

const ENV_VARS = {
  BASE_URL: env.BASE_URL,
  REDDIT_AUTH_BASE_URL: env.REDDIT_AUTH_BASE_URL,
  REDDIT_AUTH_REDIRECT_URL: env.REDDIT_AUTH_REDIRECT_URL,
  REDDIT_CLIENT_SECRET: env.REDDIT_CLIENT_SECRET,
  REDDIT_CLIENT_SECRET_BASE64_ENCODE: env.REDDIT_CLIENT_SECRET_BASE64_ENCODE,
};

export default ENV_VARS;
